# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - f9webdev03

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://f9devcontreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d3e85a498805460e879b8a77df7a6492 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3172a767fede4ce5a1bb410aa8e49eb2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: f9devcontreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3e85a498805460e879b8a77df7a6492 }}/f9_tournament:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'f9webdev03'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e463da39670640bda2158ef20aab614d }}
        images: 'f9devcontreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3e85a498805460e879b8a77df7a6492 }}/f9_tournament:${{ github.sha }}'